import type { Scheme, Variant } from "@charcuterie/tokens"
import {
  buildFirstPaintRule,
  daylight,
} from "@charcuterie/tokens"

import {
  type AxisKey,
  firstPaintAxesScript,
  pickAxes,
} from "./themeAxes.ts"

/**
 * **The theme, before anything renders** — the `previewHead`
 * transformer every Charcuterie Storybook installs.
 *
 * `@charcuterie/tokens`' `variables.css` defines every `--color-*`
 * under `[data-scheme]` and gives `:root` no colour fallback. So a
 * document with none of these attributes is not "light scheme" — it
 * is **no theme at all**, every `var(--color-…)` resolves to the
 * empty string, and the page falls through to stock Storybook
 * white. On `storybook.octen.dev` the cold load is the normal case
 * (it deep-links straight at a docs path), so this is load-bearing,
 * not belt-and-braces. See
 * `charcuterie/docs/decisions/2026-08-03-the-theme-axes-are-written-at-preview-bootstrap.md`.
 *
 * Two tags, two jobs:
 *
 * - the `<style>` is the fleet's first-paint rule, generated by
 *   `@charcuterie/tokens` so it cannot be hand-copied wrong. It is
 *   a `var()` **fallback**, never a flat literal: an inline
 *   `<style>` is unlayered, unlayered CSS beats every `@layer`, and
 *   a bare hex would outrank `bg-surface-base` forever and pin the
 *   canvas against every toolbar flip
 *   (`2026-07-31-tokens-ships-the-first-paint-snippet.md`);
 * - the `<script>` writes the chosen attributes onto `<html>` while
 *   the head is still parsing, so the stylesheet resolves against a
 *   themed document the first time it is read.
 *
 * The seed is static by nature. Keeping the *toolbar* live on a
 * story-less page is `installThemeAxes`' job, in the preview.
 *
 * @example
 *   // main.ts
 *   import { buildPreviewHead } from "@charcuterie/storybook-config"
 *   const config = {
 *     previewHead: buildPreviewHead({ axes: ["density", "scheme"] }),
 *   }
 */
export const buildPreviewHead = ({
  variant = daylight,
  scheme = "dark",
  axes,
}: {
  /** The token variant whose surfaces paint the pre-token instant. Defaults to `daylight`. */
  variant?: Variant
  /** The scheme the fallback hex branches on. Defaults to `dark`. */
  scheme?: Scheme
  /** Which axes to seed. Omit for all three. */
  axes?: readonly AxisKey[]
} = {}): ((head: string) => string) => {
  const seededAxes = axes ? pickAxes(axes) : undefined

  return (head: string) =>
    `${head}
    <style>${buildFirstPaintRule(variant, scheme)}</style>
    <script>${firstPaintAxesScript(seededAxes)}</script>`
}
