/**
 * Downloads the three **shipped** faces and writes the `@font-face`
 * sheet that goes out with the package.
 *
 * This is the survivor of the M5 bake-off's fetch script. That one
 * pulled fourteen families into `packages/docs` so they could be
 * compared; this one pulls the three that won, into the package
 * consumers actually install.
 *
 * Self-hosted rather than CDN-linked, inherited from image-viewer's
 * `2026-06-30-self-host-fonts-locally`: a kiosk Pi waiting on
 * fonts.gstatic.com before it can paint is the round-trip that
 * decision removed, and a design system that ships a CDN dependency
 * hands that cost to every consumer at once.
 *
 * All three are SIL OFL, which is the reason they can live in a
 * public package at all — the owner's preferred mono, Dank Mono, is
 * paid and cannot. See
 * `docs/decisions/2026-07-30-the-shipped-mono-is-victor-mono.md`.
 *
 * Latin only. The fleet is an English-language homelab, and the
 * Cyrillic/Greek/Vietnamese slices are dead bytes on an ePaper
 * display.
 *
 * Run: `yarn workspace @charcuterie/tokens fetch:fonts`. Idempotent.
 */

import {
  mkdir,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

/**
 * A modern-browser UA is load-bearing: the css2 endpoint content-
 * negotiates, and Node's default UA gets TrueType back instead of
 * woff2.
 */
const BROWSER_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"

/**
 * `slug` names the files on disk, because Google's hashed
 * filenames say nothing about what they contain and a reviewer
 * should be able to tell Outfit from Victor Mono without opening
 * them.
 */
const FAMILIES = [
  {
    // Vernon Adams / Cyreal. Headings.
    query: "Baloo+2:wght@400..800",
    slug: "baloo2",
  },
  {
    // Rodrigo Fuenzalida (Chile). Body.
    query: "Outfit:wght@100..900",
    slug: "outfit",
  },
  {
    // Rune Bjørnerås (Norway). Mono, with the italic — its cursive
    // italic is most of why it beat the other OFL monos.
    query: "Victor+Mono:ital,wght@0,100..700;1,100..700",
    slug: "victormono",
  },
]

const HERE = dirname(fileURLToPath(import.meta.url))
const PACKAGE_DIR = dirname(HERE)
const FONT_DIR = join(PACKAGE_DIR, "fonts")
const SHEET = join(PACKAGE_DIR, "src", "fonts.css")

const isLatinBlock = (block: string) =>
  /\/\*\s*latin(-ext)?\s*\*\//.test(block)

const main = async () => {
  /**
   * Cleared rather than overwritten: Google's filenames contain a
   * content hash, so a refresh writes *new* names and leaves the
   * old ones orphaned in the package forever.
   */
  await rm(FONT_DIR, { force: true, recursive: true })
  await mkdir(FONT_DIR, { recursive: true })

  const sheets: string[] = []

  for (const { query, slug } of FAMILIES) {
    const response = await fetch(
      `https://fonts.googleapis.com/css2?family=${query}&display=swap`,
      { headers: { "User-Agent": BROWSER_USER_AGENT } },
    )

    if (!response.ok) {
      throw new Error(
        `${slug}: ${response.status} from css2`,
      )
    }

    const blocks = (await response.text())
      .split(/(?=\/\*\s*[a-z-]+\s*\*\/)/)
      .filter(isLatinBlock)

    if (blocks.length === 0) {
      throw new Error(
        `${slug}: no latin subset in the response`,
      )
    }

    let index = 0

    for (const block of blocks) {
      let rewritten = block

      for (const [, url] of block.matchAll(
        /url\((https:[^)]+\.woff2)\)/g,
      )) {
        const name = `${slug}-${index}.woff2`
        index += 1

        const file = await fetch(url, {
          headers: { "User-Agent": BROWSER_USER_AGENT },
        })

        if (!file.ok) {
          throw new Error(
            `${name}: ${file.status} from gstatic`,
          )
        }

        await writeFile(
          join(FONT_DIR, name),
          Buffer.from(await file.arrayBuffer()),
        )

        /**
         * Relative to the sheet, so the same URL resolves whether a
         * consumer's bundler is rewriting it or a browser is
         * fetching `dist/fonts.css` directly. `copyFonts.ts` keeps
         * `fonts/` beside the sheet in `dist` for exactly this.
         */
        rewritten = rewritten.replace(
          url,
          `./fonts/${name}`,
        )
        console.log(`  ${name}`)
      }

      sheets.push(rewritten.trim())
    }

    console.log(`${slug} ✓`)
  }

  const header = [
    "/* GENERATED by scripts/fetchFonts.ts — do not hand-edit.",
    " *",
    " * The three shipped faces, self-hosted, latin subsets only:",
    " * Baloo 2 (headings), Outfit (body), Victor Mono (code).",
    " * All SIL OFL. Re-run the script to refresh.",
    " *",
    " * Consumers import this as `@charcuterie/tokens/fonts.css`.",
    " * It is a separate entry point from `theme.css` on purpose: a",
    " * Satori consumer wants the woff2 and no CSS at all, and an",
    " * app that has already loaded these faces some other way",
    " * should not be forced to download them twice.",
    " */",
    "",
  ].join("\n")

  await writeFile(
    SHEET,
    `${header}${sheets.join("\n\n")}\n`,
  )

  const written = await readdir(FONT_DIR)
  console.log(
    `\n${written.length} woff2 + ${sheets.length} @font-face blocks → src/fonts.css`,
  )
}

await main()
