/**
 * Pulls the M5 font candidates down from Google Fonts as
 * **self-hosted** woff2 plus a local `@font-face` sheet.
 *
 * Self-hosted, not CDN-linked, because the fleet already settled
 * that question once: image-viewer's
 * `2026-06-30-self-host-fonts-locally` is locked, and a kiosk Pi
 * that waits on fonts.gstatic.com before it can paint text is the
 * same round-trip that decision removed. A design system that
 * ships a CDN dependency hands that cost to every consumer.
 *
 * Latin only. The fleet is an English-language homelab, and the
 * Cyrillic/Greek/Vietnamese slices are dead bytes on an ePaper
 * display.
 *
 * Run: `node scripts/fetchCandidateFonts.ts` from `packages/docs`.
 * Idempotent — re-running overwrites, so it doubles as the
 * refresh path when a candidate is added or dropped.
 */

import { mkdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

/**
 * A modern-browser UA is load-bearing: the css2 endpoint content-
 * negotiates, and Node's default UA gets TrueType back instead of
 * woff2.
 */
const BROWSER_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"

/**
 * Every candidate family, with the variable axis range we
 * actually use. Requesting a range (`100..900`) rather than a
 * list gets one variable file per subset instead of nine static
 * ones.
 */
const FAMILIES = [
  // Rasmus Andersson (Sweden). The screen-first neutral.
  "Inter:wght@100..900",
  // Adobe (US). What image-viewer already runs, one major on.
  "Source+Sans+3:wght@200..900",
  // Undercase Type (US). The display serif — opsz drives the
  // optical size, so headings get the display cut for free.
  "Fraunces:opsz,wght@9..144,100..900",
  // Mathieu Triay (UK). The expressive grotesque.
  "Bricolage+Grotesque:opsz,wght@12..96,200..800",
  // US Web Design System (US government, public domain).
  "Public+Sans:wght@100..900",
  // JetBrains (Czech Republic). The mono for all four pairings.
  "JetBrains+Mono:wght@100..800",
]

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT_DIR = join(HERE, "..", "public", "fonts")

/** `/* latin *\/` and `/* latin-ext *\/` blocks only. */
const isLatinBlock = (block: string) =>
  /\/\*\s*latin(-ext)?\s*\*\//.test(block)

const slugify = (url: string) => {
  const [family, , file] = url.split("/").slice(-3)
  return `${family}-${file}`
}

const main = async () => {
  await mkdir(OUT_DIR, { recursive: true })

  const sheets: string[] = []

  for (const family of FAMILIES) {
    const href = `https://fonts.googleapis.com/css2?family=${family}&display=swap`
    const response = await fetch(href, {
      headers: { "User-Agent": BROWSER_USER_AGENT },
    })

    if (!response.ok) {
      throw new Error(
        `${family}: ${response.status} from css2`,
      )
    }

    const css = await response.text()

    /**
     * Split on the subset comments Google emits, so each
     * `@font-face` keeps the `unicode-range` that belongs to it.
     * Dropping a block is safe; rewriting one is not.
     */
    const blocks = css
      .split(/(?=\/\*\s*[a-z-]+\s*\*\/)/)
      .filter(isLatinBlock)

    if (blocks.length === 0) {
      throw new Error(
        `${family}: no latin subset in the response`,
      )
    }

    for (const block of blocks) {
      let rewritten = block
      const urls = [
        ...block.matchAll(/url\((https:[^)]+\.woff2)\)/g),
      ]

      for (const [, url] of urls) {
        const name = slugify(url)
        const file = await fetch(url, {
          headers: { "User-Agent": BROWSER_USER_AGENT },
        })

        if (!file.ok) {
          throw new Error(
            `${name}: ${file.status} from gstatic`,
          )
        }

        await writeFile(
          join(OUT_DIR, name),
          Buffer.from(await file.arrayBuffer()),
        )
        rewritten = rewritten.replace(url, `/fonts/${name}`)
        console.log(`  ${name}`)
      }

      sheets.push(rewritten.trim())
    }

    console.log(
      `${family.split(":")[0].replaceAll("+", " ")} ✓`,
    )
  }

  const header = [
    "/* GENERATED by scripts/fetchCandidateFonts.ts — do not hand-edit.",
    " *",
    " * Self-hosted woff2 for the M5 font bake-off. Latin subsets",
    " * only. Re-run the script to refresh or to add a candidate.",
    " */",
    "",
  ].join("\n")

  await writeFile(
    join(OUT_DIR, "candidates.css"),
    `${header}${sheets.join("\n\n")}\n`,
  )
  console.log(
    `\n${sheets.length} @font-face blocks → public/fonts/candidates.css`,
  )
}

await main()
