import {
  buildFirstPaintRule,
  daylight,
} from "@charcuterie/tokens"
import type { StorybookConfig } from "@storybook/react-vite"
import tailwindcss from "@tailwindcss/vite"
import remarkGfm from "remark-gfm"
import { mergeConfig } from "vite"

import { firstPaintAxesScript } from "./themeAxes.ts"

const config: StorybookConfig = {
  // **`.mdx` before `.stories.tsx`, deliberately.**
  //
  // An attached MDX file (`<Meta of={…} />`) is indexed where its
  // specifier sits, not hoisted the way an `autodocs` entry is — so
  // listing the stories first put every component's `Docs` entry
  // *below* its stories in the sidebar, where nobody looks for it.
  // Sorting cannot fix it either: the sidebar follows index order
  // and the index follows this array.
  stories: [
    "../src/**/*.mdx",
    "../src/**/*.stories.{ts,tsx}",
    // Stories live next to their component, in `@charcuterie/ui` —
    // matching mux-magic, where `Component.tsx` / `.stories.tsx` /
    // `.mdx` / `.test.tsx` are siblings. This package is only the
    // host; nothing about the components lives here.
    "../../ui/src/**/*.mdx",
    "../../ui/src/**/*.stories.tsx",
  ],
  addons: [
    {
      name: "@storybook/addon-docs",
      // MDX is CommonMark by default, and a GitHub-flavoured table
      // is not CommonMark — so `| Attribute | Values |` rendered as
      // a paragraph of literal pipe characters. It reads as a
      // Markdown typo rather than a missing plugin, which is why
      // `Tokens/Overview` shipped that way: the source is correct
      // and every other block on the page renders.
      options: {
        mdxPluginOptions: {
          mdxCompileOptions: {
            remarkPlugins: [remarkGfm],
          },
        },
      },
    },
    "@storybook/addon-a11y",
    // `@storybook/addon-themes` used to be here, for `data-scheme`
    // alone. It is gone: it wrote its attribute from a decorator's
    // `useEffect`, so it could not theme a page with no story, and
    // running two of the three axes through a mechanism we own and
    // the third through an addon's internals meant the one that
    // broke was the one we could not fix. `preview.tsx` now declares
    // a `scheme` global beside `density` and `variant`, and one
    // writer serves all three.
    "@storybook/addon-vitest",
    // Answers one of the plan's open questions: the pseudo-states
    // addon does support Storybook 10 — it version-matches the
    // installed 10.5.5 exactly. Without it, an `AllStates` story
    // cannot show hover or active at all, and "trust me, the hover
    // colour is fine" is not a design review.
    "storybook-addon-pseudo-states",
  ],
  core: {
    disableTelemetry: true,
  },
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  /**
   * **The theme, before anything renders.**
   *
   * The axes used to be written by story *decorators*, which meant
   * a docs page with no story on it — `Tokens/Overview`, all prose
   * — never got them. `variables.css` defines every `--color-*`
   * under `[data-scheme]` and gives `:root` no colour fallback, so
   * a missing attribute is not "light scheme", it is **no theme at
   * all**: measured cold, `--color-surface-base` came back as the
   * empty string and the page fell through to stock Storybook
   * white. Clicking any story then stamped the attributes onto the
   * shared preview document and nothing removed them, which is why
   * navigating *back* showed a correctly dark page and the bug
   * looked like it did not exist. On `storybook.octen.dev` the
   * cold load is the normal case — it deep-links straight at a docs
   * path. See
   * `docs/decisions/2026-08-03-the-theme-axes-are-written-at-preview-bootstrap.md`.
   *
   * Two tags, doing two different jobs:
   *
   * - the `<style>` is the fleet's first-paint rule, generated by
   *   `@charcuterie/tokens` — a `var()` **fallback**, never a flat
   *   literal, because an inline `<style>` is unlayered and a flat
   *   hex would outrank `bg-surface-base` forever and pin the
   *   canvas against every toolbar flip
   *   (`2026-07-31-tokens-ships-the-first-paint-snippet.md`);
   * - the `<script>` writes the three attributes onto `<html>`
   *   while the head is still parsing, so the stylesheet resolves
   *   against a themed document the first time it is read rather
   *   than a frame later.
   *
   * The seed is static by nature. Keeping the *toolbar* working on
   * a story-less page is `preview.tsx`'s job — it subscribes to the
   * globals events on the preview channel rather than waiting for a
   * story to render.
   */
  previewHead: (head) =>
    `${head}
    <style>${buildFirstPaintRule(daylight, "dark")}</style>
    <script>${firstPaintAxesScript}</script>`,
  // Tailwind v4 has to run here, not just in an app, because the
  // `@theme` block that turns `--color-*` into utilities lives in
  // `@charcuterie/tokens/theme.css`. Without this plugin the
  // stories render unstyled and the toolbars appear to do nothing.
  viteFinal: async (storybookViteConfig) =>
    mergeConfig(storybookViteConfig, {
      plugins: [tailwindcss()],
    }),
}

export default config
